title: My blog
author: joshua
email: joshua537.nit@gmail.com
description: this is description about my content

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
